/// Flutter icons BBirdIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BBirdIcons
///      fonts:
///       - asset: fonts/BBirdIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BBirdIcons {
  BBirdIcons._();

  static const _kFontFam = 'BBirdIcons';
  static const String? _kFontPkg = null;

  static const IconData icon_calendar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_delete = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_moon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_plus = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_sun = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
